-- 系统设置模板 SQL
-- 复制以下 INSERT 语句到数据库中执行，为每个配置项添加 template 字段

-- 站点配置模板
INSERT INTO `system_setting` (`tag`, `name`, `content`, `template`) VALUES ('site_config', '站点配置', '{"site_name": "Gmall Pro"}', '{"form": [{"label": "启用站点", "type": "switch", "field": "enableSite"}, {"label": "站点名称", "type": "input", "field": "siteName", "placeholder": "请输入站点名称", "maxlength": 50, "showWordLimit": true}, {"label": "站点域名", "type": "input", "field": "siteDomain", "placeholder": "请输入站点域名", "maxlength": 100, "showWordLimit": true}, {"label": "站点Logo", "type": "upload", "field": "siteLogo", "accept": ".jpg,.jpeg,.png,.gif,.svg", "limit": 1}, {"label": "站点描述", "type": "textarea", "field": "siteDescription", "placeholder": "请输入站点描述", "rows": 3, "maxlength": 200, "showWordLimit": true}, {"label": "联系邮箱", "type": "input", "field": "contactEmail", "placeholder": "请输入联系邮箱", "maxlength": 100, "showWordLimit": true}, {"label": "联系电话", "type": "input", "field": "contactPhone", "placeholder": "请输入联系电话", "maxlength": 20, "showWordLimit": true}, {"label": "版权信息", "type": "input", "field": "copyright", "placeholder": "请输入版权信息", "maxlength": 100, "showWordLimit": true}, {"label": "ICP备案号", "type": "input", "field": "icpRecord", "placeholder": "请输入ICP备案号", "maxlength": 50, "showWordLimit": true}, {"label": "公安备案号", "type": "input", "field": "policeRecord", "placeholder": "请输入公安备案号", "maxlength": 50, "showWordLimit": true}, {"label": "SEO标题", "type": "input", "field": "seoTitle", "placeholder": "请输入SEO标题", "maxlength": 100, "showWordLimit": true}, {"label": "SEO关键词", "type": "input", "field": "seoKeywords", "placeholder": "请输入SEO关键词", "maxlength": 200, "showWordLimit": true}, {"label": "SEO描述", "type": "textarea", "field": "seoDescription", "placeholder": "请输入SEO描述", "rows": 3, "maxlength": 300, "showWordLimit": true}]}');

-- 微信配置模板
INSERT INTO `system_setting` (`tag`, `name`, `content`, `template`) VALUES ('wechat', '微信配置', '{}', '{"form": [{"label": "启用微信支付", "type": "switch", "field": "enableWechat"}, {"label": "微信支付商户号", "type": "input", "field": "wechatMerchantId", "placeholder": "请输入微信支付商户号"}, {"label": "微信支付API密钥(V2)", "type": "input", "field": "wechatApiKey", "placeholder": "请输入微信支付API密钥(V2)", "type": "password", "showPassword": true}, {"label": "微信支付API密钥(V3)", "type": "input", "field": "wechatApiKeyV3", "placeholder": "请输入微信支付API密钥(V3)", "type": "password", "showPassword": true}, {"label": "API证书序列号", "type": "input", "field": "wechatCertSerialNo", "placeholder": "请输入API证书序列号"}, {"label": "API证书私钥(PEM格式)", "type": "upload", "field": "wechatPrivateKey", "accept": ".pem,.key", "limit": 1}, {"label": "微信支付平台证书(PEM格式)", "type": "upload", "field": "wechatPlatformCert", "accept": ".pem,.crt", "limit": 1}, {"label": "微信支付回调URL", "type": "input", "field": "wechatCallbackUrl", "placeholder": "请输入微信支付回调URL"}]}');

-- 支付宝配置模板
INSERT INTO `system_setting` (`tag`, `name`, `content`, `template`) VALUES ('alipay', '支付宝配置', '{}', '{"form": [{"label": "启用支付宝", "type": "switch", "field": "enableAlipay"}, {"label": "支付宝APPID", "type": "input", "field": "alipayAppId", "placeholder": "请输入支付宝APPID"}, {"label": "支付宝私钥", "type": "upload", "field": "alipayPrivateKey", "accept": ".pem,.key", "limit": 1}, {"label": "支付宝公钥", "type": "upload", "field": "alipayPublicKey", "accept": ".pem,.crt", "limit": 1}, {"label": "支付宝回调URL", "type": "input", "field": "alipayCallbackUrl", "placeholder": "请输入支付宝回调URL"}]}');

-- 短信设置模板
INSERT INTO `system_setting` (`tag`, `name`, `content`, `template`) VALUES ('sms', '短信设置', 'null', '{"form": [{"label": "短信服务商", "type": "select", "field": "smsProvider", "placeholder": "请选择短信服务商", "options": [{"label": "阿里云", "value": "aliyun"}, {"label": "腾讯云", "value": "tencent"}, {"label": "华为云", "value": "huawei"}]}, {"label": "API密钥ID", "type": "input", "field": "apiKeyId", "placeholder": "请输入API密钥ID"}, {"label": "API密钥Secret", "type": "input", "field": "apiKeySecret", "placeholder": "请输入API密钥Secret", "type": "password", "showPassword": true}, {"label": "短信签名", "type": "input", "field": "smsSign", "placeholder": "请输入短信签名"}, {"label": "验证码模板ID", "type": "input", "field": "verifyCodeTemplateId", "placeholder": "请输入验证码模板ID"}, {"label": "通知短信模板ID", "type": "input", "field": "noticeTemplateId", "placeholder": "请输入通知短信模板ID"}, {"label": "营销短信模板ID", "type": "input", "field": "marketingTemplateId", "placeholder": "请输入营销短信模板ID"}, {"label": "短信发送频率限制(秒)", "type": "inputNumber", "field": "smsSendInterval", "min": 1, "max": 3600, "placeholder": "请输入短信发送频率限制"}]}');

-- 打印设置模板
INSERT INTO `system_setting` (`tag`, `name`, `content`, `template`) VALUES ('print', '打印设置', 'null', '{"form": [{"label": "默认打印机", "type": "input", "field": "defaultPrinter", "placeholder": "请输入默认打印机名称"}, {"label": "打印方向", "type": "radioGroup", "field": "printOrientation", "options": [{"label": "纵向", "value": "portrait"}, {"label": "横向", "value": "landscape"}]}, {"label": "纸张大小", "type": "select", "field": "paperSize", "placeholder": "请选择纸张大小", "options": [{"label": "A4", "value": "A4"}, {"label": "A5", "value": "A5"}, {"label": "热敏纸80mm", "value": "80mm"}, {"label": "热敏纸58mm", "value": "58mm"}]}, {"label": "打印份数", "type": "inputNumber", "field": "printCopies", "min": 1, "max": 10, "placeholder": "请输入打印份数"}, {"label": "打印速度", "type": "select", "field": "printSpeed", "placeholder": "请选择打印速度", "options": [{"label": "低速", "value": "low"}, {"label": "中速", "value": "medium"}, {"label": "高速", "value": "high"}]}, {"label": "打印浓度", "type": "slider", "field": "printDensity", "min": 1, "max": 10, "marks": {"1": "淡", "5": "中", "10": "浓"}}, {"label": "自动打印订单", "type": "switch", "field": "autoPrintOrder"}, {"label": "自动打印发货单", "type": "switch", "field": "autoPrintDelivery"}]}');
